# Generated by Django 5.0.1 on 2024-01-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HospitalBedsModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bedId", models.CharField(max_length=100)),
                ("totalCapacity", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PatientsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_system.hospitalbedsmodels",
                    ),
                ),
            ],
        ),
    ]
