# Generated by Django 5.1.7 on 2025-04-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_store_custo_last_na_e6a359_idx_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='membership',
            new_name='payment_status',
        ),
    ]
