# Generated by Django 5.2.1 on 2025-05-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
