# Generated by Django 4.0.2 on 2022-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('foundation_date', models.DateField()),
                ('trophies_count', models.IntegerField(default=0)),
                ('league_title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
