# Generated by Django 4.0.2 on 2022-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs_app', '0002_clube_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='club_logo',
            field=models.ImageField(default='img\\default.png', upload_to=''),
        ),
    ]
