# Generated by Django 4.0.2 on 2022-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_course_attenders_course_sessions_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
