# Generated by Django 5.0.1 on 2024-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=2, unique=True)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BloodBankPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("blood_group", models.CharField(max_length=2)),
                ("daily_requirement", models.IntegerField()),
                ("days_in_hospital", models.IntegerField()),
            ],
        ),
    ]
