# Generated by Django 4.0.2 on 2022-02-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=30)),
                ('course_teacher_fullname', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
            ],
        ),
    ]
