# Generated by Django 4.0.2 on 2022-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_rename_course_description_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attenders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
