# Generated by Django 4.0.2 on 2022-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_user_information_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
