version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      - ELASTIC_PASSWORD=12345

  flask_app:
    build: "/"
    image: flask_main
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - elasticsearch